INSERT INTO STREAM_SERVICE (NAME) VALUES ('Netflix');
INSERT INTO STREAM_SERVICE (NAME) VALUES ('Amazon Prime Video');

INSERT INTO SERIES (STREAMING_ENTITY_ID, NAME, IMDB_ID, COUNTRY, MAX_SEASONS, YEAR_FROM, YEAR_TO, IN_PRODUCTION, DESCRIPTION) VALUES (2, 'Breaking Bad', 0903747, 'USA', 6, 2008, 2013, false, 'Drogen, viele Drogen');

INSERT INTO EPISODE (SERIES_ENTITY_ID, NAME, SEASON, NUMBER, IMDB_ID) VALUES (1, 'Pilot', 1, 1, 0959621);